[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/Bitcoin/ATMs/PR"
  to = "/cryptocurrencies.html"
  status = 200

[[redirects]]
  from = "/Bitcoin/ATMs/*/PR"
  to = "/neighborhoods.html"
  status = 200 